BulkyWeb/Areas/Admin/Controllers/OrderController.cs
using BulkyWeb.DataAccess.Repository.IRepository;
using BulkyWeb.Models;
using BulkyWeb.Models.ViewModel;
using BulkyWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using System.Diagnostics;
using System.Security.Claims;

namespace BulkyWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize]
	public class OrderController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderVM OrderVM { get; set; }
		public OrderController(IUnitOfWork unitOfWork) { 
			_unitOfWork = unitOfWork;
		}
		public IActionResult Index()
		{
			return View();
		}
        public IActionResult Details(int id)
        {
            var orderHeaderobj = _unitOfWork.OrderHeader.Get(u => u.Id == id);
            double totalAmount=0;
            OrderVM = new()
            {
                
                OrderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == id, includeProperties : "ApplicationUser"),
                OrderDetails = _unitOfWork.OrderDetail.GetAll(u => u.OrderId == id, includeProperties:"Product"),
                Coupon = _unitOfWork.Coupon.Get(u => u.CouponCode == orderHeaderobj.CouponCode),
            };
            foreach(var item in OrderVM.OrderDetails) { 
                int count = item.Count;
                double price = item.Price;
                totalAmount += (count * price);
            }
            ViewBag.TotalAmount = totalAmount;
            return View(OrderVM);
        }
        [HttpPost]
        [Authorize(Roles =SD.Role_Admin+","+SD.Role_Employee)]
        public IActionResult UpdateOrderDetail()
        {
            var orderHeaderFrom = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeaderFrom.Name = OrderVM.OrderHeader.Name;
            orderHeaderFrom.StreetAddress = OrderVM.OrderHeader.StreetAddress;
            orderHeaderFrom.State = OrderVM.OrderHeader.State;
            orderHeaderFrom.City = OrderVM.OrderHeader.City;
            orderHeaderFrom.PostalCode = OrderVM.OrderHeader.PostalCode;
            orderHeaderFrom.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
            if (!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier))
            {
                orderHeaderFrom.Carrier = OrderVM.OrderHeader.Carrier;
            }
            if (!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
            {
                orderHeaderFrom.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            }
            _unitOfWork.OrderHeader.Update(orderHeaderFrom);
            _unitOfWork.Save();
            TempData["success"] = "Order Detail Update Succesfully";
            return RedirectToAction(nameof(Details),new {Id = orderHeaderFrom.Id});
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult StartProcessing()
        {
            _unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, SD.StatusInProcess);
            _unitOfWork.Save();
            TempData["success"] = "Order Status Inprocess Update Succesfully";
            return RedirectToAction(nameof(Details),new { Id = OrderVM.OrderHeader.Id});
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult ShipOrder()
        {
            var orderFromdb = _unitOfWork.OrderHeader.Get(u=>u.Id ==  OrderVM.OrderHeader.Id);
            orderFromdb.Carrier = OrderVM.OrderHeader.Carrier;
            orderFromdb.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            orderFromdb.OrderStatus = SD.StatusShipping;
            orderFromdb.ShippingDate = DateTime.Now;

            if(orderFromdb.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                orderFromdb.PaymentDueDate = (DateTime.Now.AddDays(30));
            }
            _unitOfWork.OrderHeader.Update(orderFromdb);
            _unitOfWork.Save();
            TempData["success"] = "Order Status Shipped Update Succesfully";
            return RedirectToAction(nameof(Details), new { Id = OrderVM.OrderHeader.Id });
        }
        [HttpPost]
       
        public IActionResult CancelOrder()
        {
            var orderFromdb = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);

            if(orderFromdb.PaymentStatus == SD.PaymentStatusApproved)
            {
                var options = new RefundCreateOptions { 
                    Reason = RefundReasons.RequestedByCustomer,
                    PaymentIntent = orderFromdb.PaymentIntentId
                };
                var services = new RefundService();
                Refund refund = services.Create(options);

                _unitOfWork.OrderHeader.UpdateStatus(orderFromdb.Id, SD.StatusCancelled, SD.StatusRefunded);
               
            }
            else
            {
                _unitOfWork.OrderHeader.UpdateStatus(orderFromdb.Id, SD.StatusCancelled, SD.StatusCancelled);
            }
            _unitOfWork.Save();
            TempData["success"] = "Order Status Cancelled Succesfully";
            return RedirectToAction(nameof(Details), new { Id = OrderVM.OrderHeader.Id });
        }
        [ActionName("Details")]
        [HttpPost]
        public IActionResult Detail_Pay_Now()
        {
            OrderVM.OrderHeader = _unitOfWork.OrderHeader.Get(u=>u.Id == OrderVM.OrderHeader.Id, includeProperties: "ApplicationUser");
            OrderVM.OrderDetails = _unitOfWork.OrderDetail.GetAll(u=>u.OrderId == OrderVM.OrderHeader.Id , includeProperties: "Product");

            //stripe payment
            var domain = Request.Scheme+"://"+Request.Host.Value+"/";
            var options = new SessionCreateOptions
            {
                SuccessUrl = domain + $"admin/Order/OrderConfirmation?OrderHeaderId={OrderVM.OrderHeader.Id}",
                CancelUrl = domain + $"admin/order/details?OrderId={OrderVM.OrderHeader.Id}",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
            };

            foreach (var item in OrderVM.OrderDetails)
            {
                var sessionLineItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions()
                    {
                        UnitAmount = (long)(item.Price * 100), //its can include in here about amount
                        Currency = "INR",
                        ProductData = new SessionLineItemPriceDataProductDataOptions()
                        {
                            Name = item.Product.Title
                        }

                    },
                    Quantity = item.Count

                };
                options.LineItems.Add(sessionLineItem);

            }
            var service = new SessionService();
            Session session = service.Create(options);
            _unitOfWork.OrderHeader.UpdateStripePaymentID(OrderVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303); 
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult StatusDelivery()
        {
            var orderobj= _unitOfWork.OrderHeader.Get(u=>u.Id==OrderVM.OrderHeader.Id);
            orderobj.OrderStatus = SD.StatusDelivered;
            orderobj.DeliveryDate = DateTime.Now;
            _unitOfWork.OrderHeader.Update(orderobj);
            _unitOfWork.Save();
            TempData["success"] = "Order Status Delivery Update Succesfully";
            return RedirectToAction(nameof(Details), new { Id = OrderVM.OrderHeader.Id });
        }
        [HttpPost]
        public IActionResult ReturnRequest()
        {
            var orderobj = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            orderobj.OrderStatus = SD.ReturnRequest;
            
            _unitOfWork.OrderHeader.Update(orderobj);
            _unitOfWork.Save();
            TempData["success"] = "Sent Return Order Request";
            return RedirectToAction(nameof(Details), new { Id = OrderVM.OrderHeader.Id });
        }
        [HttpPost]
        public IActionResult OrderReturnConfirmation()
        {
            var orderobj = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            var userobj = _unitOfWork.ApplicationUser.Get(u => u.Id == orderobj.ApplicationUserId);
            orderobj.OrderStatus = SD.StatusReturned;
            orderobj.PaymentStatus = SD.StatusRefunded;
            if(orderobj.PaymentMethod == SD.PaymentMethodOnline)
            {
                if(userobj.Wallet == null)
                {
                    userobj.Wallet = 0;
                }
                userobj.Wallet += (int)orderobj.OrderTotal;
            }
            orderobj.ReturnDate = DateTime.Now;
            _unitOfWork.OrderHeader.Update(orderobj);
            _unitOfWork.ApplicationUser.Update(userobj);
            _unitOfWork.Save();
            TempData["success"] = "Order Return  Succesfully";
            return RedirectToAction(nameof(Details), new { Id = OrderVM.OrderHeader.Id });
        }
        public IActionResult OrderConfirmation(int OrderHeaderId)
        {
            OrderHeader orderHeader =
                _unitOfWork.OrderHeader.Get(u => u.Id == OrderHeaderId);
            if (orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                var services = new SessionService();
                Session session = services.Get(orderHeader.SessionId);
                if (session.PaymentStatus.ToLower() == "paid")
                {
                    _unitOfWork.OrderHeader.UpdateStripePaymentID(OrderHeaderId, session.Id, session.PaymentIntentId);

BulkyWeb/Areas/Admin/Controllers/UserController.cs
using BulkyWeb.DataAccess.Data;
using BulkyWeb.DataAccess.Repository.IRepository;
using BulkyWeb.Models;
using BulkyWeb.Models.ViewModel;
using BulkyWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        /* private readonly IUnitOfWork _unitOfWork;*/
        /*public UserController(IUnitOfWork db) {
            _unitOfWork = db;
        }*/
        public UserController(ApplicationDbContext applicationDbContext)
        {
            _context = applicationDbContext;
        }
        public IActionResult Index()
        {
            List<ApplicationUser> userfromdb = _context.ApplicationUsers.Include(u=>u.company).ToList();

            return View(userfromdb);
        }
       
        #region API CALLS
        [HttpGet]
        public IActionResult Get()
        {
            List<ApplicationUser> userfromdb = _context.ApplicationUsers.Include(u=>u.company).ToList();
            return Json(new { data = userfromdb });
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            return Json(new { success = true, errrorMessage = "Delete is succesfully" });
        }
        #endregion
    }

}

BulkyWeb/Controllers/CategoryController.cs
using BulkyWeb.DataAccess.Data;
using BulkyWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace BulkyWeb.Controllers
{
    public class CategoryController : Controller
    {
        public readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db) { 
            _db = db;
        }
        public IActionResult Index()
        {
            List<Category> category = _db.categories.ToList();
            return View(category);
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Category obj) {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The display order cannot exactly same");
            }
            if (ModelState.IsValid)
            {
                _db.categories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Category Created Successfully";
                return RedirectToAction("Index");
            }
           
            return View();
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDb1 = _db.categories.FirstOrDefault(u => u.Id == id);
            /*Category? CategoryFromDb = _db.Categories.Find(id);*//*
            Category? CategoryFromDb2 = _db.Categories.Where(u=>u.Id==id).FirstOrDefault();*/
            if (CategoryFromDb1 == null)
            {
                return NotFound();
            }
            return View(CategoryFromDb1);
        }
        [HttpPost]
        public IActionResult Edit(Category obj)
        {

            if (ModelState.IsValid)
            {
               _db.categories.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Category Edit Successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDb1 = _db.categories.FirstOrDefault(u => u.Id == id);
            /*Category? CategoryFromDb = _db.Categories.Find(id);*//*
            Category? CategoryFromDb2 = _db.Categories.Where(u=>u.Id==id).FirstOrDefault();*/
            if (CategoryFromDb1 == null)
            {
                return NotFound();
            }
            return View(CategoryFromDb1);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Category? obj = _db.categories.FirstOrDefault(u => u.Id == id);

            if (obj == null)
            {
                return NotFound();
            }
            _db.categories.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Category delete Successfully";
            return RedirectToAction("Index");

        }

    }
}

BulkyWeb/ViewComponents/ShoppingCartViewComponent.cs
using BulkyWeb.DataAccess.Repository.IRepository;
using BulkyWeb.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        public readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork) { 
            _unitOfWork = unitOfWork;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.sessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.sessionCart,
                    _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).Count());
                }
                
                return View(HttpContext.Session.GetInt32(SD.sessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

BulkyWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    
    @await RenderSectionAsync("css", required: false)

    <link rel="stylesheet" href="~/BulkyWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                   <img src="/images/book.png" style="width:50px"/> LearnClub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="Order" asp-action="Index">OrderMangement</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="DashBoard" asp-action="Details">DashBoard</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Coupon" asp-action="Index">Coupon</a>
                                    </li>
                                  
                                    <li><hr class="dropdown-divider"></li>
                                <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                </li>
                               @*  <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                                </li> *@
                                    <li>
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                </ul>

                            </li>
                        }
                      
                            <li class="nav-item">
                                <a class="nav-link " asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                   @await Component.InvokeAsync("ShoppingCart")
                                </a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="CustomerCoupon" asp-action="Index">
                                <i class="bi bi-ticket-detailed"></i> Coupon
                            </a>
                        </li>
                        <li class="nav-item">
                            
                        </li>
                  
                    </ul>
                    <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="UserProfile">
                        <img class="rounded-5" width="50px" src="https://www.pngall.com/wp-content/uploads/5/Profile-Male-PNG.png" />
                    </a>
                  
                    
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer  bg-primary">
        <div class="container text-white-50 text-center">
            Made With <i class="bi bi-heart-fill"></i> by Sreehari
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/product.js" asp-append-version="true"></script>
    <script src="~/js/company.js" asp-append-version="true"></script>
    <script src="~/js/user.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="https://cdn.tiny.cloud/1/8ro4fww41buo6grq6wjpfozo5itxg3vk9bbvn726t66lzll3/tinymce/6/plugins.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>

}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}