BulkyWeb/Areas/Admin/Controllers/CouponController.cs
using BulkyWeb.DataAccess.Repository.IRepository;
using BulkyWeb.Models;
using BulkyWeb.Models.ViewModel;
using BulkyWeb.Utility;
using Microsoft.AspNetCore.Mvc;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CouponController : Controller
    {
        public IUnitOfWork _unitOfWork;
        [BindProperty]
        public CouponVM CouponVM { get; set; }
        public CouponController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Coupon> coupon = _unitOfWork.Coupon.GetAll().ToList();

            return View(coupon);
        }
        public IActionResult AddCoupon()
        {
            return View();
        }
        [HttpPost]
        
        public IActionResult AddCoupon(Coupon coupon)
        {
            if(coupon != null)
            {
                coupon.IsValid = SD.CouponValid;
                _unitOfWork.Coupon.Add(coupon);
                _unitOfWork.Save();
            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int id)
        {
           Coupon coupon = _unitOfWork.Coupon.Get(u=>u.Id == id);
            return View(coupon);
        }
        [HttpPost]
        public IActionResult Edit(Coupon coupon)
        {
           if (coupon != null)
            {
                _unitOfWork.Coupon.Update(coupon);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(coupon);
        }
        public IActionResult Delete(int id)
        {
            Coupon coupon = _unitOfWork.Coupon.Get(u=>u.Id == id);
            return View(coupon);
        }
        [HttpPost]
        public IActionResult Delete(Coupon coupon)
        {
            if (coupon == null)
            {
                NotFound();
            }
            _unitOfWork.Coupon.Remove(coupon);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
        
            
    }
}

BulkyWeb/Controllers/CategoryController.cs
using BulkyWeb.DataAccess.Data;
using BulkyWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace BulkyWeb.Controllers
{
    public class CategoryController : Controller
    {
        public readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db) { 
            _db = db;
        }
        public IActionResult Index()
        {
            List<Category> category = _db.categories.ToList();
            return View(category);
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Category obj) {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The display order cannot exactly same");
            }
            if (ModelState.IsValid)
            {
                _db.categories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Category Created Successfully";
                return RedirectToAction("Index");
            }
           
            return View();
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDb1 = _db.categories.FirstOrDefault(u => u.Id == id);
            /*Category? CategoryFromDb = _db.Categories.Find(id);*//*
            Category? CategoryFromDb2 = _db.Categories.Where(u=>u.Id==id).FirstOrDefault();*/
            if (CategoryFromDb1 == null)
            {
                return NotFound();
            }
            return View(CategoryFromDb1);
        }
        [HttpPost]
        public IActionResult Edit(Category obj)
        {

            if (ModelState.IsValid)
            {
               _db.categories.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Category Edit Successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? CategoryFromDb1 = _db.categories.FirstOrDefault(u => u.Id == id);
            /*Category? CategoryFromDb = _db.Categories.Find(id);*//*
            Category? CategoryFromDb2 = _db.Categories.Where(u=>u.Id==id).FirstOrDefault();*/
            if (CategoryFromDb1 == null)
            {
                return NotFound();
            }
            return View(CategoryFromDb1);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Category? obj = _db.categories.FirstOrDefault(u => u.Id == id);

            if (obj == null)
            {
                return NotFound();
            }
            _db.categories.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Category delete Successfully";
            return RedirectToAction("Index");

        }

    }
}

BulkyWeb/Areas/Admin/Views/Coupon/AddCoupon.cshtml
@model Coupon

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Add Coupon</h2>
               
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <div class="border p-3">
                @*<div asp-validation-summary="ModelOnly"></div>*@
                <div class="form-floating py-2 col-12">
                    <input asp-for="CouponCode" class="form-control border-0 shadow" />
                    <label asp-for="CouponCode" class="ms-2"></label>
                    <span asp-validation-for="CouponCode" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="MinAmout" class="form-control border-0 shadow" />
                    <label asp-for="MinAmout" class="ms-2"></label>
                    <span asp-validation-for="MinAmout" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DiscountAmout" class="form-control border-0 shadow" />
                    <label asp-for="DiscountAmout" class="ms-2"></label>
                    <span asp-validation-for="DiscountAmout" class="text-danger"></span>
                </div>

                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Create</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-area="Admin" asp-controller="Coupon" asp-action="Index" class="btn btn-outline-primary border  form-control">
                            Back to List
                        </a>
                    </div>
                </div>


            </div>
        </form>
    </div>
</div>




@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BulkyWeb/Areas/Admin/Views/Coupon/Delete.cshtml
@model Coupon
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Product</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" id="yourFormId">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">
                <div class="form-floating py-2 col-12">
                    <input asp-for="CouponCode" disabled class="form-control border-0 shadow" />
                    <label asp-for="CouponCode" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="MinAmout" disabled class="form-control border-0 shadow" />
                    <label asp-for="MinAmout" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DiscountAmout" disabled class="form-control border-0 shadow" />
                    <label asp-for="DiscountAmout" class="ms-2"></label>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="IsValid" disabled class="form-control border-0 shadow" />
                    <label asp-for="IsValid" class="ms-2"></label>
                </div>

                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button  type="submit" class="btn btn-danger form-control">Delete</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Coupon" asp-action="Index" class="btn btn-secondary border  form-control">
                            Back to List
                        </a>
                    </div>
                </div>


            </div>
        </form>
    </div>
</div>

BulkyWeb/Areas/Admin/Views/Coupon/Edit.cshtml
@model Coupon
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Edit Category</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">
                @*<div asp-validation-summary="ModelOnly"></div>*@
                <div class="form-floating py-2 col-12">
                    <input asp-for="CouponCode" class="form-control border-0 shadow" />
                    <label asp-for="CouponCode" class="ms-2"></label>
                    <span asp-validation-for="CouponCode" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="MinAmout" class="form-control border-0 shadow" />
                    <label asp-for="MinAmout" class="ms-2"></label>
                    <span asp-validation-for="MinAmout" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DiscountAmout" class="form-control border-0 shadow" />
                    <label asp-for="DiscountAmout" class="ms-2"></label>
                    <span asp-validation-for="DiscountAmout" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                   <div>
                        <input type="radio" asp-for="IsValid" name="IsValid" value="valid" />
                        <label class="ms-2">Valid</label>
                   </div>
                   <div>
                        <input type="radio" asp-for="IsValid" name="IsValid" value="Invalid" />
                        <label class="ms-2">InValid</label>
                   </div>
                  
                    <span asp-validation-for="IsValid" class="text-danger"></span>
                </div>

                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Update</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Category" asp-action="Index" class="btn btn-secondary border  form-control">
                            Back to List
                        </a>
                    </div>
                </div>


            </div>
        </form>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

BulkyWeb/Areas/Admin/Views/Coupon/Index.cshtml
@model List<Coupon> 

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Coupon List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-area="Admin" asp-controller="Coupon" asp-action="AddCoupon" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i>  Add New Coupon
                </a>
            </div>
        </div>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Coupon Code
                    </th>
                    <th>
                        Discount Amount
                    </th>
                    <th>
                        Minimum Amount
                    </th>
                    <th>
                        Is Valid
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.CouponCode</td>
                        <td>
                            @obj.DiscountAmout
                        </td>
                        <td>
                            @obj.MinAmout
                        </td>
                        <td>
                            @obj.IsValid
                        </td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-area="Admin" asp-controller="Coupon" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                    <i class="bi bi-pencil-square"></i>   Edit
                                </a>
                             
                                <a id="deleteLink" asp-controller="Coupon" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>